-- AddForeignKey
ALTER TABLE "Cart" ADD CONSTRAINT "Cart_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Cart" ADD CONSTRAINT "Cart_rice_id_fkey" FOREIGN KEY ("rice_id") REFERENCES "Rice"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
